name: Publish Docker Image to GHCR

on:
  push:
    branches:
      - main  # Tự động build khi push lên nhánh main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Cần quyền 'write' để push image

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }} # Tên user/org của bạn
          password: ${{ secrets.GITHUB_TOKEN }}  # Token tự động của GitHub

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/cloudflared-gen-controller:latest
            ghcr.io/${{ github.repository_owner }}/cloudflared-gen-controller:${{ github.sha }}