name: Publish Docker Image to GHCR

on:
  push:
    branches:
      - main  # Automatically build when pushing to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Required to push to GHCR

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Read version from VERSION file
        id: version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            VERSION=${{ steps.version.outputs.VERSION }}
            CLOUDFLARED_VERSION=latest
            DOCKER_GEN_VERSION=0.7.7
          tags: |
            ghcr.io/${{ github.repository_owner }}/cloudflared-gen-controller:latest
            ghcr.io/${{ github.repository_owner }}/cloudflared-gen-controller:v${{ steps.version.outputs.VERSION }}
            ghcr.io/${{ github.repository_owner }}/cloudflared-gen-controller:${{ github.sha }}